#ifndef __NT_TERM_H__
#define __NT_TERM_H__

struct nt_term
{
    /* Stores escape sequences generated by a specific terminal emulator
     * when pressing a specific key(F1, F2, DEL...).
     * The indexing inside the array must adhere to nt_esc_defs.h */
    char** esc_key_seqs;

    /* Stores escape sequences sent to a specific terminal emulator
     * in order to invoke various functions(changing the color, clearing
     * the screen...).
     * The indexing inside the array must adhere to nt_esc_defs.h */
    char** esc_func_seqs;
};

int nt_term_init();

const struct nt_term* nt_term_get_used();

void nt_term_destroy();

#endif // __NT_TERM_H__
