#ifndef _NT_ESC_DEFS_H_
#define _NT_ESC_DEFS_H_

/* Escape keys */

#define NT_ESC_KEY_F1 0
#define NT_ESC_KEY_F2 1
#define NT_ESC_KEY_F3 2
#define NT_ESC_KEY_F4 3
#define NT_ESC_KEY_F5 4
#define NT_ESC_KEY_F6 5
#define NT_ESC_KEY_F7 6
#define NT_ESC_KEY_F8 7
#define NT_ESC_KEY_F9 8
#define NT_ESC_KEY_F10 9
#define NT_ESC_KEY_F11 10
#define NT_ESC_KEY_F12 11
#define NT_ESC_KEY_ARR_UP 12
#define NT_ESC_KEY_ARR_RIGHT 13
#define NT_ESC_KEY_ARR_DOWN 14
#define NT_ESC_KEY_ARR_LEFT 15
#define NT_ESC_KEY_INSERT 16
#define NT_ESC_KEY_DEL 17
#define NT_ESC_KEY_HOME 18
#define NT_ESC_KEY_END 19
#define NT_ESC_KEY_PG_UP 20
#define NT_ESC_KEY_PG_DOWN 21
#define NT_ESC_KEY_STAB 22
#define __NT_ESC_KEY_END 23

/* Escape keys encoded into codepoints(after the unicode characters) */

#define _NT_ESC_CODEPOINT_BASE 0x10FFFF // Last unicode codepoint

#define NT_ESC_CODEPOINT_F1 (_NT_ESC_CODEPOINT_BASE + 1 + NT_ESC_KEY_F1)
#define NT_ESC_CODEPOINT_F2 (_NT_ESC_CODEPOINT_BASE + 1 + NT_ESC_KEY_F2)
#define NT_ESC_CODEPOINT_F3 (_NT_ESC_CODEPOINT_BASE + 1 + NT_ESC_KEY_F3)
#define NT_ESC_CODEPOINT_F4 (_NT_ESC_CODEPOINT_BASE + 1 + NT_ESC_KEY_F4)
#define NT_ESC_CODEPOINT_F5 (_NT_ESC_CODEPOINT_BASE + 1 + NT_ESC_KEY_F5)
#define NT_ESC_CODEPOINT_F6 (_NT_ESC_CODEPOINT_BASE + 1 + NT_ESC_KEY_F6)
#define NT_ESC_CODEPOINT_F7 (_NT_ESC_CODEPOINT_BASE + 1 + NT_ESC_KEY_F7)
#define NT_ESC_CODEPOINT_F8 (_NT_ESC_CODEPOINT_BASE + 1 + NT_ESC_KEY_F8)
#define NT_ESC_CODEPOINT_F9 (_NT_ESC_CODEPOINT_BASE + 1 + NT_ESC_KEY_F9)
#define NT_ESC_CODEPOINT_F10 (_NT_ESC_CODEPOINT_BASE + 1 + NT_ESC_KEY_F10)
#define NT_ESC_CODEPOINT_F11 (_NT_ESC_CODEPOINT_BASE + 1 + NT_ESC_KEY_F11)
#define NT_ESC_CODEPOINT_F12 (_NT_ESC_CODEPOINT_BASE + 1 + NT_ESC_KEY_F12)
#define NT_ESC_CODEPOINT_ARR_UP (_NT_ESC_CODEPOINT_BASE + 1 + NT_ESC_KEY_ARR_UP)
#define NT_ESC_CODEPOINT_ARR_RIGHT (_NT_ESC_CODEPOINT_BASE + 1 + NT_ESC_KEY_ARR_RIGHT)
#define NT_ESC_CODEPOINT_ARR_DOWN (_NT_ESC_CODEPOINT_BASE + 1 + NT_ESC_KEY_ARR_DOWN)
#define NT_ESC_CODEPOINT_ARR_LEFT (_NT_ESC_CODEPOINT_BASE + 1 + NT_ESC_KEY_ARR_LEFT)
#define NT_ESC_CODEPOINT_INSERT (_NT_ESC_CODEPOINT_BASE + 1 + NT_ESC_KEY_INSERT)
#define NT_ESC_CODEPOINT_DEL (_NT_ESC_CODEPOINT_BASE + 1 + NT_ESC_KEY_DEL)
#define NT_ESC_CODEPOINT_HOME (_NT_ESC_CODEPOINT_BASE + 1 + NT_ESC_KEY_HOME)
#define NT_ESC_CODEPOINT_END (_NT_ESC_CODEPOINT_BASE + 1 + NT_ESC_KEY_END)
#define NT_ESC_CODEPOINT_PG_UP (_NT_ESC_CODEPOINT_BASE + 1 + NT_ESC_KEY_PG_UP)
#define NT_ESC_CODEPOINT_PG_DOWN (_NT_ESC_CODEPOINT_BASE + 1 + NT_ESC_KEY_PG_DOWN)
#define NT_ESC_CODEPOINT_STAB (_NT_ESC_CODEPOINT_BASE + 1 + NT_ESC_KEY_STAB)
#define NT_ESC_CODEPOINT_UNKNOWN (_NT_ESC_CODEPOINT_BASE + 1 + __NT_ESC_KEY_END)

#define _NT_ESC_KEY_TO_CODEPOINT(key) ((key) + 1 + _NT_ESC_CODEPOINT_BASE)

/* Escape functions */

#define NT_ESC_FUNC_SHOW_CURSOR 0
#define NT_ESC_FUNC_HIDE_CURSOR 1
#define NT_ESC_FUNC_MOVE_CURSOR 2
#define NT_ESC_FUNC_SET_FG_C8 3
#define NT_ESC_FUNC_SET_FG_C256 4
#define NT_ESC_FUNC_SET_FG_RGB 5
#define NT_ESC_FUNC_SET_BG_C8 6
#define NT_ESC_FUNC_SET_BG_C256 7
#define NT_ESC_FUNC_SET_BG_RGB 8
#define NT_ESC_FUNC_SET_STYLE_BOLD 9
#define NT_ESC_FUNC_SET_STYLE_FAINT 10
#define NT_ESC_FUNC_SET_STYLE_ITALIC 11
#define NT_ESC_FUNC_SET_STYLE_UNDERLINE 12
#define NT_ESC_FUNC_SET_STYLE_BLINK 13
#define NT_ESC_FUNC_SET_STYLE_REVERSE 14
#define NT_ESC_FUNC_SET_STYLE_HIDDEN 15
#define NT_ESC_FUNC_SET_STYLE_STRIKETHROUGH 16
#define NT_ESC_FUNC_RESET_GFX 17
#define NT_ESC_FUNC_ERASE_SCREEN 18
#define NT_ESC_FUNC_ERASE_SCROLLBACK 19 
#define NT_ESC_FUNC_ERASE_LINE 20
#define NT_ESC_FUNC_ENTER_ALT_BUFF 21
#define NT_ESC_FUNC_EXIT_ALT_BUFF 22
#define __NT_ESC_FUNC_END 23

#endif // _NT_ESC_DEFS_H_
