#ifndef _NT_ESC_DEFS_H_
#define _NT_ESC_DEFS_H_

/* Escape keys */

#define NT_ESC_KEY_F1 1
#define NT_ESC_KEY_F2 2
#define NT_ESC_KEY_F3 3
#define NT_ESC_KEY_F4 4
#define NT_ESC_KEY_F5 5
#define NT_ESC_KEY_F6 6
#define NT_ESC_KEY_F7 7
#define NT_ESC_KEY_F8 8
#define NT_ESC_KEY_F9 9
#define NT_ESC_KEY_F10 10
#define NT_ESC_KEY_F11 11
#define NT_ESC_KEY_F12 12
#define NT_ESC_KEY_ARR_UP 13
#define NT_ESC_KEY_ARR_RIGHT 14
#define NT_ESC_KEY_ARR_DOWN 15
#define NT_ESC_KEY_ARR_LEFT 16
#define NT_ESC_KEY_INSERT 17
#define NT_ESC_KEY_DEL 18
#define NT_ESC_KEY_HOME 19
#define NT_ESC_KEY_END 20
#define NT_ESC_KEY_PG_UP 21
#define NT_ESC_KEY_PG_DOWN 22
#define NT_ESC_KEY_STAB 23 // Must be last because of NT_ESC_CODEPOINT_UNKNOWN

/* Escape keys encoded into codepoints(after the unicode characters) */

#define NT_ESC_CODEPOINT_BASE 0x10FFFF // Last unicode codepoint

#define NT_ESC_CODEPOINT_F1 (NT_ESC_CODEPOINT_BASE + NT_ESC_KEY_F1)
#define NT_ESC_CODEPOINT_F2 (NT_ESC_CODEPOINT_BASE + NT_ESC_KEY_F2)
#define NT_ESC_CODEPOINT_F3 (NT_ESC_CODEPOINT_BASE + NT_ESC_KEY_F3)
#define NT_ESC_CODEPOINT_F4 (NT_ESC_CODEPOINT_BASE + NT_ESC_KEY_F4)
#define NT_ESC_CODEPOINT_F5 (NT_ESC_CODEPOINT_BASE + NT_ESC_KEY_F5)
#define NT_ESC_CODEPOINT_F6 (NT_ESC_CODEPOINT_BASE + NT_ESC_KEY_F6)
#define NT_ESC_CODEPOINT_F7 (NT_ESC_CODEPOINT_BASE + NT_ESC_KEY_F7)
#define NT_ESC_CODEPOINT_F8 (NT_ESC_CODEPOINT_BASE + NT_ESC_KEY_F8)
#define NT_ESC_CODEPOINT_F9 (NT_ESC_CODEPOINT_BASE + NT_ESC_KEY_F9)
#define NT_ESC_CODEPOINT_F10 (NT_ESC_CODEPOINT_BASE + NT_ESC_KEY_F10)
#define NT_ESC_CODEPOINT_F11 (NT_ESC_CODEPOINT_BASE + NT_ESC_KEY_F11)
#define NT_ESC_CODEPOINT_F12 (NT_ESC_CODEPOINT_BASE + NT_ESC_KEY_F12)
#define NT_ESC_CODEPOINT_ARR_UP (NT_ESC_CODEPOINT_BASE + NT_ESC_KEY_ARR_UP)
#define NT_ESC_CODEPOINT_ARR_RIGHT (NT_ESC_CODEPOINT_BASE + NT_ESC_KEY_ARR_RIGHT)
#define NT_ESC_CODEPOINT_ARR_DOWN (NT_ESC_CODEPOINT_BASE + NT_ESC_KEY_ARR_DOWN)
#define NT_ESC_CODEPOINT_ARR_LEFT (NT_ESC_CODEPOINT_BASE + NT_ESC_KEY_ARR_LEFT)
#define NT_ESC_CODEPOINT_INSERT (NT_ESC_CODEPOINT_BASE + NT_ESC_KEY_INSERT)
#define NT_ESC_CODEPOINT_DEL (NT_ESC_CODEPOINT_BASE + NT_ESC_KEY_DEL)
#define NT_ESC_CODEPOINT_HOME (NT_ESC_CODEPOINT_BASE + NT_ESC_KEY_HOME)
#define NT_ESC_CODEPOINT_END (NT_ESC_CODEPOINT_BASE + NT_ESC_KEY_END)
#define NT_ESC_CODEPOINT_PG_UP (NT_ESC_CODEPOINT_BASE + NT_ESC_KEY_PG_UP)
#define NT_ESC_CODEPOINT_PG_DOWN (NT_ESC_CODEPOINT_BASE + NT_ESC_KEY_PG_DOWN)
#define NT_ESC_CODEPOINT_STAB (NT_ESC_CODEPOINT_BASE + NT_ESC_KEY_STAB)
#define NT_ESC_CODEPOINT_UNKNOWN (NT_ESC_CODEPOINT_BASE + NT_ESC_KEY_STAB + 1)

/* Escape functions */

#define NT_ESC_FUNC_SHOW_CURSOR 1
#define NT_ESC_FUNC_HIDE_CURSOR 2
#define NT_ESC_FUNC_MOVE_CURSOR 3
#define NT_ESC_FUNC_SET_FG_C8 4
#define NT_ESC_FUNC_SET_FG_C256 5
#define NT_ESC_FUNC_SET_FG_RGB 6
#define NT_ESC_FUNC_SET_BG_C8 7
#define NT_ESC_FUNC_SET_BG_C256 8
#define NT_ESC_FUNC_SET_BG_RGB 9
#define NT_ESC_FUNC_SET_STYLE_BOLD 10
#define NT_ESC_FUNC_SET_STYLE_FAINT 11
#define NT_ESC_FUNC_SET_STYLE_ITALIC 12
#define NT_ESC_FUNC_SET_STYLE_UNDERLINE 13
#define NT_ESC_FUNC_SET_STYLE_BLINK 14
#define NT_ESC_FUNC_SET_STYLE_REVERSE 15
#define NT_ESC_FUNC_SET_STYLE_HIDDEN 16
#define NT_ESC_FUNC_SET_STYLE_STRIKETHROUGH 17
#define NT_ESC_FUNC_RESET_GFX 18
#define NT_ESC_FUNC_ERASE_SCREEN 19
#define NT_ESC_FUNC_ERASE_SCROLLBACK 20
#define NT_ESC_FUNC_ERASE_LINE 21
#define NT_ESC_FUNC_ENTER_ALT_BUFF 22
#define NT_ESC_FUNC_EXIT_ALT_BUFF 23

#endif // _NT_ESC_DEFS_H_
