#ifndef _NT_ESC_CODEPOINTS_H_
#define _NT_ESC_CODEPOINTS_H_

#include <stdint.h>

/* Encode esc keys on keyboard(F1, F2 ... F12, DEL...) into codepoints. */

#define NT_ESC_CODEPOINT_BASE 0x10FFFF // Last unicode codepoint

#define NT_ESC_CODEPOINT_ARROW_UP (NT_ESC_CODEPOINT_BASE + 1)
#define NT_ESC_CODEPOINT_ARROW_RIGHT (NT_ESC_CODEPOINT_BASE + 2)
#define NT_ESC_CODEPOINT_ARROW_DOWN (NT_ESC_CODEPOINT_BASE + 3)
#define NT_ESC_CODEPOINT_ARROW_LEFT (NT_ESC_CODEPOINT_BASE + 4)
#define NT_ESC_CODEPOINT_F1 (NT_ESC_CODEPOINT_BASE + 5)
#define NT_ESC_CODEPOINT_F2 (NT_ESC_CODEPOINT_BASE + 6)
#define NT_ESC_CODEPOINT_F3 (NT_ESC_CODEPOINT_BASE + 8)
#define NT_ESC_CODEPOINT_F4 (NT_ESC_CODEPOINT_BASE + 8)
#define NT_ESC_CODEPOINT_F5 (NT_ESC_CODEPOINT_BASE + 9)
#define NT_ESC_CODEPOINT_F6 (NT_ESC_CODEPOINT_BASE + 10)
#define NT_ESC_CODEPOINT_F7 (NT_ESC_CODEPOINT_BASE + 11)
#define NT_ESC_CODEPOINT_F8 (NT_ESC_CODEPOINT_BASE + 12)
#define NT_ESC_CODEPOINT_F9 (NT_ESC_CODEPOINT_BASE + 13)
#define NT_ESC_CODEPOINT_F10 (NT_ESC_CODEPOINT_BASE + 14)
#define NT_ESC_CODEPOINT_F11 (NT_ESC_CODEPOINT_BASE + 15)
#define NT_ESC_CODEPOINT_F12 (NT_ESC_CODEPOINT_BASE + 16)
#define NT_ESC_CODEPOINT_DELETE (NT_ESC_CODEPOINT_BASE + 17)
#define NT_ESC_CODEPOINT_INSERT (NT_ESC_CODEPOINT_BASE + 18)
#define NT_ESC_CODEPOINT_END (NT_ESC_CODEPOINT_BASE + 19)
#define NT_ESC_CODEPOINT_HOME (NT_ESC_CODEPOINT_BASE + 20)
#define NT_ESC_CODEPOINT_PAGE_DOWN (NT_ESC_CODEPOINT_BASE + 21)
#define NT_ESC_CODEPOINT_PAGE_UP (NT_ESC_CODEPOINT_BASE + 22)
#define NT_ESC_CODEPOINT_STAB (NT_ESC_CODEPOINT_BASE + 23)
#define NT_ESC_CODEPOINT_UNKNOWN (NT_ESC_CODEPOINT_BASE + 24)

#endif // _NT_ESC_CODEPOINTS_H_
