/*
 * Copyright (c) 2025 Novak Stevanović
 * Licensed under the MIT License. See LICENSE file in project root.
 */
#ifndef _NT_INTERNAL_H_
#define _NT_INTERNAL_H_

#include "nt_status.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Internally used. */
enum nt_esc_func
{
    NT_ESC_FUNC_CURSOR_SHOW,
    NT_ESC_FUNC_CURSOR_HIDE,
    NT_ESC_FUNC_CURSOR_MOVE, // 2 params
    NT_ESC_FUNC_FG_SET_C8, // 1 param
    NT_ESC_FUNC_FG_SET_C256, // 1 param
    NT_ESC_FUNC_FG_SET_RGB, // 3 params
    NT_ESC_FUNC_FG_SET_DEFAULT,
    NT_ESC_FUNC_BG_SET_C8, // 1 param
    NT_ESC_FUNC_BG_SET_C256, // 1 param
    NT_ESC_FUNC_BG_SET_RGB, // 3 params
    NT_ESC_FUNC_BG_SET_DEFAULT,
    NT_ESC_FUNC_STYLE_SET_BOLD,
    NT_ESC_FUNC_STYLE_SET_FAINT,
    NT_ESC_FUNC_STYLE_SET_ITALIC,
    NT_ESC_FUNC_STYLE_SET_UNDERLINE,
    NT_ESC_FUNC_STYLE_SET_BLINK,
    NT_ESC_FUNC_STYLE_SET_REVERSE,
    NT_ESC_FUNC_STYLE_SET_HIDDEN,
    NT_ESC_FUNC_STYLE_SET_STRIKETHROUGH,
    NT_ESC_FUNC_GFX_RESET, // (!)
    NT_ESC_FUNC_ERASE_SCREEN,
    NT_ESC_FUNC_ERASE_SCROLLBACK, // CHECK IF STANDARD
    NT_ESC_FUNC_ERASE_LINE,
    NT_ESC_FUNC_ALT_BUFF_ENTER,
    NT_ESC_FUNC_ALT_BUFF_EXIT,
    NT_ESC_FUNC_MOUSE_ENABLE,
    NT_ESC_FUNC_MOUSE_DISABLE,
    NT_ESC_FUNC_OTHER // Must be last because internally used as count
};

struct nt_term_info
{
    /* Stores escape sequences generated by a specific terminal emulator
     * when pressing a specific key(F1, F2, DEL...).
     * The indexing inside the array must adhere to nt_esc.h */
    char** esc_key_seqs;

    /* Stores escape sequences sent to a specific terminal emulator
     * in order to invoke various functions(changing the color, clearing
     * the screen...).
     * The indexing inside the array must adhere to nt_esc.h */
    char** esc_func_seqs;

    char* name;
};

typedef enum nt_term_color_count
{
    NT_TERM_COLOR_C8,
    NT_TERM_COLOR_C256,
    NT_TERM_COLOR_TC,
    NT_TERM_COLOR_OTHER // Must be last because internally used as count
} nt_term_color_count;

/* Detects terminal(based on $TERM) and color palette(based on $TERM, $COLORTERM).
 * Sets internal values that can be retrieved by getter funcs below.
 *
 * STATUS CODES:
 * 1) NT_SUCCESS,
 * 2) NT_ERR_INIT_TERM_ENV - $TERM is not set. */
void _nt_term_init(nt_status* out_status);

/* Returns NT_TERM_COUNT if not set. */
struct nt_term_info _nt_term_get_used();

/* Returns NT_TERM_COLOR_COUNT if not set. */
nt_term_color_count _nt_term_get_color_count();

void _nt_term_deinit();

#define SET_OUT(out_param, out_val) \
    if((out_param) != NULL) ((*out_param)) = out_val;

#ifdef __cplusplus
}
#endif

#endif // _NT_INTERNAL_H_
