/*
 * Copyright (c) 2025 Novak Stevanović
 * Licensed under the MIT License. See LICENSE file in project root.
 */
#ifndef NT_INTERNAL_H
#define NT_INTERNAL_H

#include "nt_shared.h"
#include "nt_error.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Internally used. */
enum nt_esc_func
{
    NT_ESC_FUNC_CURSOR_SHOW,
    NT_ESC_FUNC_CURSOR_HIDE,
    NT_ESC_FUNC_CURSOR_MOVE, // 2 params
    NT_ESC_FUNC_FG_SET_C8, // 1 param
    NT_ESC_FUNC_FG_SET_C256, // 1 param
    NT_ESC_FUNC_FG_SET_RGB, // 3 params
    NT_ESC_FUNC_FG_SET_DEFAULT,
    NT_ESC_FUNC_BG_SET_C8, // 1 param
    NT_ESC_FUNC_BG_SET_C256, // 1 param
    NT_ESC_FUNC_BG_SET_RGB, // 3 params
    NT_ESC_FUNC_BG_SET_DEFAULT,
    NT_ESC_FUNC_STYLE_SET_BOLD,
    NT_ESC_FUNC_STYLE_SET_FAINT,
    NT_ESC_FUNC_STYLE_SET_ITALIC,
    NT_ESC_FUNC_STYLE_SET_UNDERLINE,
    NT_ESC_FUNC_STYLE_SET_BLINK,
    NT_ESC_FUNC_STYLE_SET_REVERSE,
    NT_ESC_FUNC_STYLE_SET_HIDDEN,
    NT_ESC_FUNC_STYLE_SET_STRIKETHROUGH,
    NT_ESC_FUNC_GFX_RESET, // (!)
    NT_ESC_FUNC_ERASE_SCREEN,
    NT_ESC_FUNC_ERASE_SCROLLBACK, // CHECK IF STANDARD
    NT_ESC_FUNC_ERASE_LINE,
    NT_ESC_FUNC_ALT_BUFF_ENTER,
    NT_ESC_FUNC_ALT_BUFF_EXIT,
    NT_ESC_FUNC_MOUSE_ENABLE,
    NT_ESC_FUNC_MOUSE_DISABLE,
    NT_ESC_FUNC_OTHER // Must be last because internally used as count
};

struct nt_term_info
{
    /* Escape sequences generated by terminal keys such as F1 or Delete. */
    char** esc_key_seqs;

    /* Escape sequences used to invoke terminal functions. */
    char** esc_func_seqs;

    char* name;
};

typedef enum nt_term_color_count
{
    NT_TERM_COLOR_C8,
    NT_TERM_COLOR_C256,
    NT_TERM_COLOR_TC,
    NT_TERM_COLOR_OTHER // Must be last because internally used as count
} nt_term_color_count;

/* Detects the terminal and color mode from TERM and COLORTERM.
 *
 * ERROR CODES:
 * 1) NT_ERR_INIT_TERM_ENV - TERM is not set.
 * 2) NT_ERR_TERM_NOT_SUPP - The terminal was not recognized and xterm
 * compatibility was assumed. */
int nt__term_init(void);

/* Returns the selected terminal info, or a zero-initialized value if unset. */
struct nt_term_info nt__term_get_used(void);

/* Returns the selected color mode, or NT_TERM_COLOR_OTHER if unset. */
nt_term_color_count nt__term_get_color_count(void);

void nt__term_deinit(void);

#ifdef __cplusplus
}
#endif

#endif // NT_INTERNAL_H
